### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor on Windows 7

### ISSUE THREAD

**Issue by madeindjs** [phaethon/scapy#100]
I can't send any packet on **Python3 IDLE** because of this warning.

```python
>>> from scapy.all import *
WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6
>>> packet = IP(dst='10.122.25.12')/TCP(dport=80)/Raw(b'hello')
>>> ans, unans= srp(packet)
WARNING: No route found (no default route?)
Begin emission:
WARNING: No route found (no default route?)
WARNING: more No route found (no default route?)
Finished to send 1 packets.
Traceback (most recent call last):
  File "<pyshell#18>", line 1, in <module>
    ans, unans= srp(packet)
  File "C:\Users\rousseaua\AppData\Local\Programs\Python\Python35\lib\site-packages\scapy\sendrecv.py", line 368, in srp
    a,b=sndrcv(s ,x,*args,**kargs)
  File "C:\Users\rousseaua\AppData\Local\Programs\Python\Python35\lib\site-packages\scapy\arch\windows\__init__.py", line 382, in sndrcv
    os.write(1, b".")
OSError: [Errno 9] Bad file descriptor
```
I'm on:

* Windows Entreprise 64bits
* Python 3.5.2

**Comment by madeindjs** [comment]
It's seem be a rights problem. Now when i'm lauchn **Python IDLE** as administrator (like before) I've got:

~~~python
>>> from scapy.all import *
WARNING: No match between your pcap and windows network interfaces found. You probably won't be able to send packets. Deactivating unneeded interfaces and restarting Scapy might help.Check your winpcap and powershell installation, and access rights.
~~~
