### ISSUE TITLE
get_windows_if_list ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by jp281** [phaethon/scapy#108]
With python 3.4.4, used "pip3 install scapy-python3" on a Windows7 VM and I am seeing this error on "from scapy.all import *":

C:\Users\admin>pip3 list
...
pip (8.1.2)
scapy-python3 (0.18)
...

C:\Windows\system32>python
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy.all import *
WARNING: Windows support for scapy3k is currently in testing. Sniffing/sending/receiving packets should be working with
WinPcap driver and Powershell. Create issues at https://github.com/phaethon/scapy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\scapy\all.py", line 16, in <module>
    from .arch import *
  File "C:\Python34\lib\site-packages\scapy\arch\__init__.py", line 88, in <module>
    from .windows import *
  File "C:\Python34\lib\site-packages\scapy\arch\windows\__init__.py", line 198, in <module>
    ifaces.load_from_powershell()
  File "C:\Python34\lib\site-packages\scapy\arch\windows\__init__.py", line 149, in load_from_powershell
    for i in get_windows_if_list():
  File "C:\Python34\lib\site-packages\scapy\arch\windows\__init__.py", line 85, in get_windows_if_list
    name, value = [ j.strip() for j in i.split(b':') ]
ValueError: too many values to unpack (expected 2)

Here is the output from netsh show interface:
C:\Users\admin>netsh interface show interface
Admin State    State          Type             Interface Name
-------------------------------------------------------------------------
Enabled        Connected      Dedicated        Local Area Connection

**Comment by jp281** [comment]
I only need scapy-python3 for packet assembly and dissection.  In the install guide it mentioned that Win7 could be operated in "offline packet crafting/dissection".  Is there a simple way to put it into that mode instead of going down the PowerShell rat hole?

**Comment by fjjupc** [comment]
Hello there, I solved this problem in Win7 with updating my PowerShell: Windows Management Framework 4.0. 
Link: https://www.microsoft.com/en-us/download/details.aspx?id=40855

**Comment by phaethon** [comment]
Thanks @fjjupc for comment I was using latest PowerShell and was not aware of issues with earlier versions. @jp281, please, confirm this solves the issue for you, too, and we can close it.

**Comment by jp281** [comment]
After upgrading to PSVersion = 4.0, it is still failing at the same spot:

![image](https://cloud.githubusercontent.com/assets/22085544/19783639/4d4ee4c0-9c58-11e6-8f70-0d8f8569aa97.png)

**Comment by jp281** [comment]
Note that this is a Windows7 VM instance running in VMWare ESX.

**Comment by fjjupc** [comment]
Well, did u reboot your instance?
Please try again in the powershell after rebooting, thanks.

**Comment by jp281** [comment]
Yes, I tried after rebooting the Win7 VM, after uninstalling/reinstalling scapy-python3 with pip3.  It still ends up with the same error.  I have tried by running python 3.4.4/scapy-python3 in a command shell as Administrator and also within the powershell:

![image](https://cloud.githubusercontent.com/assets/22085544/19814297/443f8a8c-9d03-11e6-86fb-42fca968aee9.png)

**Comment by jp281** [comment]
Note that if I "import scapy" and then issue "from scapy.all import *" I see a different error regarding pcapdnet:

![image](https://cloud.githubusercontent.com/assets/22085544/19814377/88f91436-9d03-11e6-908d-44322109d58b.png)

**Comment by gpotter2** [comment]
@jp281 Has this been fixed ?

**Comment by myrinx** [comment]
I also have this problem. installed pip3 install scapy-python3 on a windows 7 environment. I have winpcap installed, which is the problem is in the screenshot above.

**Comment by gpotter2** [comment]
That was fixed on the original version of `scapy`. Feel free to have a look at it
