### ISSUE TITLE
TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by xtr3m3rok** [phaethon/scapy#125]
p = RadioTap()/Dot11(addr1='3e:fd:64:40:c5:2d', addr2='1c:5f:2b:e8:ea:b2', addr3='1c:5f:2b:e8:ea:b2')/Dot11Deauth()

p.summary()
Out[27]: 
'RadioTap / 802.11 Management 12 1c:5f:2b:e8:ea:b2 > 3e:fd:64:40:c5:2d / Dot11Deauth'

send(p, iface='wlan1mon', inter=.2)
WARNING: Mac address to reach destination not found. Using broadcast.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-30-81d822604b98>", line 1, in <module>
    send(p, iface='wlan1mon', inter=.2)
  File "/usr/local/lib/python3.5/dist-packages/scapy/sendrecv.py", line 255, in send
    __gen_send(conf.L3socket(*args, **kargs), x, inter=inter, loop=loop, count=count,verbose=verbose, realtime=realtime)
  File "/usr/local/lib/python3.5/dist-packages/scapy/sendrecv.py", line 238, in __gen_send
    s.send(p)
  File "/usr/local/lib/python3.5/dist-packages/scapy/arch/linux.py", line 405, in send
    sx = bytes(ll(x))
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 289, in __bytes__
    return self.build()
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 357, in build
    p = self.do_build()
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 349, in do_build
    pay = self.do_build_payload()
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 341, in do_build_payload
    return self.payload.do_build()
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 346, in do_build
    pkt = self.self_build()
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 337, in self_build
    p = f.addfield(self, p, val)
  File "/usr/local/lib/python3.5/dist-packages/scapy/fields.py", line 153, in addfield
    if self._evalcond(pkt):
  File "/usr/local/lib/python3.5/dist-packages/scapy/fields.py", line 144, in _evalcond
    return self.cond(pkt)
  File "/usr/local/lib/python3.5/dist-packages/scapy/layers/dot11.py", line 130, in <lambda>
    ConditionalField(LELongField('tsft', 0), lambda pkt: pkt.getdictval('present')['TSFT']),
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 184, in getdictval
    return fld.i2dict(self, v)
  File "/usr/local/lib/python3.5/dist-packages/scapy/fields.py", line 919, in i2dict
    if x & 1:
TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'

**Comment by xtr3m3rok** [comment]
sendp(RadioTap()/
          Dot11(addr1="ff:ff:ff:ff:ff:ff",
                addr2="00:01:02:03:04:05",
                addr3="00:01:02:03:04:05")/
          Dot11Beacon(cap="ESS", timestamp=1)/
          Dot11Elt(ID="SSID", info=RandString(RandNum(1,50)))/
          Dot11Elt(ID="Rates", info='\x82\x84\x0b\x16')/
          Dot11Elt(ID="DSset", info="\x03")/
          Dot11Elt(ID="TIM", info="\x00\x01\x00\x00"),
          iface="wlan1mon", loop=1)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-40-1d35cc4d8a1b>", line 10, in <module>
    iface="wlan1mon", loop=1)
  File "/usr/local/lib/python3.5/dist-packages/scapy/sendrecv.py", line 263, in sendp
    __gen_send(conf.L2socket(iface=iface, *args, **kargs), x, inter=inter, loop=loop, count=count, verbose=verbose, realtime=realtime)
  File "/usr/local/lib/python3.5/dist-packages/scapy/sendrecv.py", line 238, in __gen_send
    s.send(p)
  File "/usr/local/lib/python3.5/dist-packages/scapy/supersocket.py", line 31, in send
    sx = bytes(x)
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 289, in __bytes__
    return self.build()
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 357, in build
    p = self.do_build()
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 346, in do_build
    pkt = self.self_build()
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 337, in self_build
    p = f.addfield(self, p, val)
  File "/usr/local/lib/python3.5/dist-packages/scapy/fields.py", line 153, in addfield
    if self._evalcond(pkt):
  File "/usr/local/lib/python3.5/dist-packages/scapy/fields.py", line 144, in _evalcond
    return self.cond(pkt)
  File "/usr/local/lib/python3.5/dist-packages/scapy/layers/dot11.py", line 130, in <lambda>
    ConditionalField(LELongField('tsft', 0), lambda pkt: pkt.getdictval('present')['TSFT']),
  File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 184, in getdictval
    return fld.i2dict(self, v)
  File "/usr/local/lib/python3.5/dist-packages/scapy/fields.py", line 919, in i2dict
    if x & 1:
TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'

**Comment by adityashinde1506** [comment]
Any fix yet?

**Comment by xtr3m3rok** [comment]
no fix (

**Comment by Pve88** [comment]
Try this: RadioTap(present=0)
packet = RadioTap(present=0) / Dot11(type=1, subtype=11, addr1=receiverAddr, addr2=transmitterAddr, ID=126)

**Comment by llazzaro** [comment]
@Pve88 solution works.

**Comment by medhasm** [comment]
@Pve88  Thank You.
