### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode' (non ascii character in my iface name/description)

### ISSUE THREAD

**Issue by Dagt** [phaethon/scapy#162]
OS Windows 8.1
Python 3.4

I'm getting the following error every time i try to send a packet:

```
ERROR: --- Error sending packets
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\scapy\arch\windows\__init__.py", line 325, in sndrcv
    pks.send(p)
  File "C:\Python34\lib\site-packages\scapy\arch\pcapdnet.py", line 399, in send
    sx = bytes(cls()/x)
  File "C:\Python34\lib\site-packages\scapy\packet.py", line 289, in __bytes__
    return self.build()
  File "C:\Python34\lib\site-packages\scapy\packet.py", line 357, in build
    p = self.do_build()
  File "C:\Python34\lib\site-packages\scapy\packet.py", line 346, in do_build
    pkt = self.self_build()
  File "C:\Python34\lib\site-packages\scapy\packet.py", line 337, in self_build
    p = f.addfield(self, p, val)
  File "C:\Python34\lib\site-packages\scapy\fields.py", line 79, in addfield
    return s+struct.pack(self.fmt, self.i2m(pkt,val))
  File "C:\Python34\lib\site-packages\scapy\layers\l2.py", line 95, in i2m
    return MACField.i2m(self, pkt, self.i2h(pkt, x))
  File "C:\Python34\lib\site-packages\scapy\layers\l2.py", line 89, in i2h
    x = conf.neighbor.resolve(pkt,pkt.payload)
  File "C:\Python34\lib\site-packages\scapy\layers\l2.py", line 38, in resolve
    return self.resolvers[k](l2inst,l3inst)
  File "C:\Python34\lib\site-packages\scapy\layers\inet.py", line 739, in <lambda>
    conf.neighbor.register_l3(Ether, IP, lambda l2,l3: getmacbyip(l3.dst))
  File "C:\Python34\lib\site-packages\scapy\layers\l2.py", line 73, in getmacbyip
    nofilter=1)
  File "C:\Python34\lib\site-packages\scapy\sendrecv.py", line 385, in srp1
    a,b=srp(*args,**kargs)
  File "C:\Python34\lib\site-packages\scapy\sendrecv.py", line 367, in srp
    s = conf.L2socket(iface=iface, filter=filter, nofilter=nofilter, type=type)
  File "C:\Python34\lib\site-packages\scapy\arch\pcapdnet.py", line 322, in __init__
    self.ins = open_pcap(iface, 1600, 0, 100)
  File "C:\Python34\lib\site-packages\scapy\arch\windows\__init__.py", line 225, in <lambda>
    pcapdnet.open_pcap = lambda iface,*args,**kargs: _orig_open_pcap(pcap_name(iface),*args,**kargs)
  File "C:\Python34\lib\site-packages\scapy\arch\pcapdnet.py", line 252, in <lambda>
    open_pcap = lambda *args,**kargs: _PcapWrapper_pypcap(*args,**kargs)
  File "C:\Python34\lib\site-packages\scapy\arch\pcapdnet.py", line 216, in __init__
    self.iface = create_string_buffer(device.encode('ascii'))
AttributeError: 'NoneType' object has no attribute 'encode'
INFO: --- Error sending packets
```

I'm using a Windows spanish version and the name/description of my wireless adapter is: 
"Adaptador de red inalámbrica Qualcomm Atheros AR5B97"
I think the problem may be the accent being a non ascii character??

**Comment by MordechaiMaman** [comment]
Did my fix solve your problem ?

**Comment by Dagt** [comment]
Yees it solve the problem!!
Thanks and sorry for the delay answering
