### ISSUE TITLE
AttributeError: 'module' object has no attribute 'AF_PACKET'

### ISSUE THREAD

**Issue by miguelmota** [phaethon/scapy#205]
trying to run example

```
>>> p = IP(dst = 'www.somesite.ex') / TCP(dport = 80) / Raw(b'Some raw bytes')
>>> sr(p)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/scapy/sendrecv.py", line 336, in sr
    s = conf.L3socket(filter=filter, iface=iface, nofilter=nofilter)
  File "/Library/Python/2.7/site-packages/scapy/supersocket.py", line 69, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))
AttributeError: 'module' object has no attribute 'AF_PACKET'
```

**Comment by alexmarder** [comment]
Has there been any progress on this? Since updating to version 0.22 I've been getting this problem on macos. This was not a problem with version 0.21.

**Comment by bmedicke** [comment]
Same issue here with Python 3. I've downgraded to 0.21 for now:
`pip3 install -I scapy-python3==0.21`

**Comment by nevsan** [comment]
+1. Same problem.

Downgrading to `0.21` works for me. I hear `BPF` should be a viable alternative for OS X.

**Comment by phaethon** [comment]
@miguelmota Your trace includes python/2.7 directory. Scapy3k (scapy-python3 package) works only with python3. Can you confirm that you are using python3?

**Comment by phaethon** [comment]
I will get to a OS X machine later this week to investigate. 
If somebody could take 0.21 code and commit by commit forward to find out the commit to blame, it would speed up fixing.

**Comment by phaethon** [comment]
There is some issue with the new CAN layer implementation. Released 0.23 temporary disabling the layer, and it should work now.

**Comment by nevsan** [comment]
0.23 works for me.

**Comment by getkub** [comment]
The issue is reoccuring on: Scapy Version 2.4.0.dev58
MacOSX

**Comment by jpie726** [comment]
Sorry for necro-posting, but [this SO answer](https://stackoverflow.com/a/7818800)(mentioned by [this answer](https://stackoverflow.com/a/38406832)) suggests that BSD-flavour distros use BPF, although the functionality is different. AF_PACKET is only available on UN*X distros, and may not be installed by default either.
