### ISSUE TITLE
windows 10 scapy python 3.6

### ISSUE THREAD

**Issue by durces** [phaethon/scapy#237]
Getting the following messages/error when installing scapy-python3 on windows 10 with python 3.6.4?
****
INFO: Can't load Python libreadline or completer
INFO: No IPv6 support in kernel
WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6
INFO: Please, report issues to https://github.com/phaethon/scapy
Traceback (most recent call last):
  File "C:\Users\zubeyde\AppData\Local\Programs\Python\Python36-32\Scripts\\scapy", line 25, in <module>
    interact()
  File "C:\Users\zubeyde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\scapy\main.py", line 293, in interact
    scapy_builtins = __import__("scapy.all",globals(),locals(),".").__dict__
  File "C:\Users\zubeyde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\scapy\all.py", line 46, in <module>
    from .crypto import *
  File "C:\Users\zubeyde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\scapy\crypto\__init__.py", line 17, in <module>
    from scapy.crypto.cert import *
  File "C:\Users\zubeyde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\scapy\crypto\cert.py", line 110, in <module>
    def _hashWrapper(hash_algo, message, backend=default_backend()):
  File "C:\Users\zubeyde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cryptography\hazmat\backends\__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Users\zubeyde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cryptography\hazmat\backends\openssl\__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Users\zubeyde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 16, in <module>
    from cryptography import utils, x509
  File "C:\Users\zubeyde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cryptography\x509\__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "C:\Users\zubeyde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cryptography\x509\base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "C:\Users\zubeyde\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cryptography\x509\extensions.py", line 13, in <module>
    from asn1crypto.keys import PublicKeyInfo
ModuleNotFoundError: No module named 'asn1crypto'

any ideas followed the process:

http://my.home-data.center/2016/10/24/python-3-5-scapy-windows-10/

and python 3.6.4

***
and
installed, uninstalled many  times using pip3.6 no resolution?

**Comment by phaethon** [comment]
The error seems to come from cryptography module. Try removing and/or reinstalling cryptography.io module.
