### ISSUE TITLE
AttributeError 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by IlyaDhtvzGhbltn** [phaethon/scapy#259]
System: Windows 10
Python: v3.7.1
kamene: v3.0.0

First, I launch kamene from cmd like this : Win+R -> cmd>kamene and got the following traceback : 
`INFO: Can't load Python libreadline or completer
INFO: No IPv6 support in kernel
WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6
INFO: Please, report issues to https://github.com/phaethon/kamene
WARNING: IPython not available. Using standard Python shell instead.
Welcome to kamene (3.0.0)`

Then I create packet like this : 

`>>> a=IP(dst="193.58.244.217")/TCP(dport=3055)/"test"
>>> a
<IP  frag=0 proto=tcp dst=143.58.254.217 |<TCP  dport=3335 |<Raw  load='test' |>>>`

and want to send it.

`>>> send(a)` and got the next traceback : 

`Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\user.i\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kamene\sendrecv.py", line 260, in send
    __gen_send(conf.L3socket(*args, **kargs), x, inter=inter, loop=loop, count=count,verbose=verbose, realtime=realtime)
  File "C:\Users\user.i\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kamene\arch\pcapdnet.py", line 321, in __init__
    self.ins = open_pcap(iface, 1600, 0, 100)
  File "C:\Users\user.i\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kamene\arch\windows\__init__.py", line 237, in <lambda>
    pcapdnet.open_pcap = lambda iface,*args,**kargs: _orig_open_pcap(pcap_name(iface),*args,**kargs)
  File "C:\Users\user.i\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kamene\arch\pcapdnet.py", line 251, in <lambda>
    open_pcap = lambda *args,**kargs: _PcapWrapper_pypcap(*args,**kargs)
  File "C:\Users\user.i\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kamene\arch\pcapdnet.py", line 215, in __init__
    self.iface = create_string_buffer(device.encode('ascii'))
AttributeError: 'NoneType' object has no attribute 'encode'`

I don't understand, where is my error ?

**Comment by chklhead** [comment]
Is this related to the PCAP/NPCAP library I have installed?
-----
I am currently running versions:
Windows 10
Python 3.6.5
Kamene 3.0.0
NPCAP 0.9983
