### ISSUE TITLE
Error when building DHCP packet

### ISSUE THREAD

**Issue by zachary822** [phaethon/scapy#29]
```
from scapy.all import *

ethernet = Ether(dst='ff:ff:ff:ff:ff:ff', type=0x800)
udp = UDP(sport=68, dport=67)
bootp = BOOTP(ciaddr='0.0.0.0', flags=1)
dhcp = DHCP(options=[("message-type", "discover"), "end"])
packet = ethernet / udp / bootp / dhcp

print(packet)
```
Running the above code will yield the error below:
```
Traceback (most recent call last):
  File "/Users/zachary/script.py", line 9, in <module>
    print(packet)
  File "/usr/local/lib/python3.5/site-packages/scapy/packet.py", line 283, in __str__
    return repr(bytes(self)) 
  File "/usr/local/lib/python3.5/site-packages/scapy/packet.py", line 285, in __bytes__
    return self.build()
  File "/usr/local/lib/python3.5/site-packages/scapy/packet.py", line 353, in build
    p = self.do_build()
  File "/usr/local/lib/python3.5/site-packages/scapy/packet.py", line 345, in do_build
    pay = self.do_build_payload()
  File "/usr/local/lib/python3.5/site-packages/scapy/packet.py", line 337, in do_build_payload
    return self.payload.do_build()
  File "/usr/local/lib/python3.5/site-packages/scapy/packet.py", line 345, in do_build
    pay = self.do_build_payload()
  File "/usr/local/lib/python3.5/site-packages/scapy/packet.py", line 337, in do_build_payload
    return self.payload.do_build()
  File "/usr/local/lib/python3.5/site-packages/scapy/packet.py", line 342, in do_build
    pkt = self.self_build()
  File "/usr/local/lib/python3.5/site-packages/scapy/packet.py", line 333, in self_build
    p = f.addfield(self, p, val)
  File "/usr/local/lib/python3.5/site-packages/scapy/fields.py", line 365, in addfield
    return s+self.i2m(pkt, val)
  File "/usr/local/lib/python3.5/site-packages/scapy/fields.py", line 362, in i2m
    x=str(x).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\x82' in position 1: ordinal not in range(128)

Process finished with exit code 1
```

**Comment by phaethon** [comment]
Yes, seems there is an issue with DHCP options field. Will check.

**Comment by zachary822** [comment]
If it makes any difference:
```
In [1]: import platform

In [2]: platform.platform()
Out[2]: 'Darwin-15.0.0-x86_64-i386-64bit'

In [7]: import sys

In [8]: sys.version
Out[8]: '3.5.0 (default, Sep 15 2015, 09:44:40) \n[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]'
```

**Comment by phaethon** [comment]
I can repeat it on Linux with python 3.5.

**Comment by phaethon** [comment]
Fix just committed

**Comment by zachary822** [comment]
As an aspiring python programmer, you are absolutely awesome!

**Comment by phaethon** [comment]
I noticed some sarcasm in your message. What's your point?

**Comment by zachary822** [comment]
Sorry to come up that way, I meant I was the aspiring python programmer, and you being awesome. I tried following the error output and couldn't figure out where the error was coming from, and you figured it out in a very short time. No sarcasm intended, genuine compliment.

**Comment by phaethon** [comment]
Thanks! I misunderstood the previous post. 
Some parts of scapy are written in a sophisticated way. It is naturally hard to debug this type of error the first time you see scapy code.
