### ISSUE TITLE
OSError: Cannot find libdnet.so

### ISSUE THREAD

**Issue by luckydonald** [phaethon/scapy#44]
```python
# pip install scrapy-python3
from scapy.layers.inet import traceroute
# next line is from tutorial
res,unans = traceroute(["www.microsoft.com","www.cisco.com","www.yahoo.com","www.wanadoo.fr","www.pacsec.com"],dport=[80,443],maxttl=20,retry=-2)
```
```python
/Users/luckydonald/Documents/Python/virtualenv3.4.3_brew.venv/bin/python3.4 /Users/luckydonald/Documents/Python/SimpleStuff/lan-utils.py
Traceback (most recent call last):
  File "/Users/luckydonald/Documents/Python/SimpleStuff/lan-utils.py", line 8, in <module>
    from scapy.layers.inet import traceroute
  File "/Users/luckydonald/Documents/Python/virtualenv3.4.3_brew.venv/lib/python3.4/site-packages/scapy/layers/inet.py", line 14, in <module>
    from scapy.layers.l2 import *
  File "/Users/luckydonald/Documents/Python/virtualenv3.4.3_brew.venv/lib/python3.4/site-packages/scapy/layers/l2.py", line 14, in <module>
    from scapy.ansmachine import *
  File "/Users/luckydonald/Documents/Python/virtualenv3.4.3_brew.venv/lib/python3.4/site-packages/scapy/ansmachine.py", line 14, in <module>
    from .sendrecv import send,sendp,sniff
  File "/Users/luckydonald/Documents/Python/virtualenv3.4.3_brew.venv/lib/python3.4/site-packages/scapy/sendrecv.py", line 13, in <module>
    import scapy.arch
  File "/Users/luckydonald/Documents/Python/virtualenv3.4.3_brew.venv/lib/python3.4/site-packages/scapy/arch/__init__.py", line 84, in <module>
    from .bsd import *
  File "/Users/luckydonald/Documents/Python/virtualenv3.4.3_brew.venv/lib/python3.4/site-packages/scapy/arch/bsd.py", line 12, in <module>
    from .unix import *
  File "/Users/luckydonald/Documents/Python/virtualenv3.4.3_brew.venv/lib/python3.4/site-packages/scapy/arch/unix.py", line 22, in <module>
    from .pcapdnet import *
  File "/Users/luckydonald/Documents/Python/virtualenv3.4.3_brew.venv/lib/python3.4/site-packages/scapy/arch/pcapdnet.py", line 22, in <module>
    from .cdnet import *
  File "/Users/luckydonald/Documents/Python/virtualenv3.4.3_brew.venv/lib/python3.4/site-packages/scapy/arch/cdnet.py", line 17, in <module>
    raise OSError("Cannot find libdnet.so")
OSError: Cannot find libdnet.so
```

Mac OSX 10.9.5
```shell
mac:SimpleStuff luckydonald$ uname -a
Darwin mac.fritz.box 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64
```
```python
Python 3.4.3 (default, Aug 10 2015, 16:40:44) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
```

**Comment by phaethon** [comment]
Currently, scapy on MacOS requires libdnet library to be installed. Go to http://libdnet.sourceforge.net/ and download/install it; or use some packaged version.
It is planned to get rid of this dependency.

**Comment by luckydonald** [comment]
Until then, maybe add a info to the readme?

**Comment by phaethon** [comment]
Added comment to Readme under installation
