### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'route'

### ISSUE THREAD

**Issue by luckydonald** [phaethon/scapy#45]
```python
# pip install scrapy-python3
from scapy.layers.inet import traceroute
# next line is from tutorial
res,unans = traceroute(["www.microsoft.com","www.cisco.com","www.yahoo.com","www.wanadoo.fr","www.pacsec.com"],dport=[80,443],maxttl=20,retry=-2)
```

```python
Traceback (most recent call last):
  File "/Users/luckydonald/Documents/Python/SimpleStuff/lan-utils.py", line 10, in <module>
    ],dport=[80,443],maxttl=20,retry=-2)
  File "/Users/luckydonald/Documents/Python/virtualenv3.4.3_brew.venv/lib/python3.4/site-packages/scapy/layers/inet.py", line 1315, in traceroute
    timeout=timeout, filter=filter, verbose=verbose, **kargs)
  File "/Users/luckydonald/Documents/Python/virtualenv3.4.3_brew.venv/lib/python3.4/site-packages/scapy/sendrecv.py", line 327, in sr
    a,b=sndrcv(s,x,*args,**kargs)
  File "/Users/luckydonald/Documents/Python/virtualenv3.4.3_brew.venv/lib/python3.4/site-packages/scapy/sendrecv.py", line 55, in sndrcv
    h = i.hashret()
  File "/Users/luckydonald/Documents/Python/virtualenv3.4.3_brew.venv/lib/python3.4/site-packages/scapy/layers/inet.py", line 377, in hashret
    return strxor(inet_aton(self.src),inet_aton(self.dst))+struct.pack("B",self.proto)+self.payload.hashret()
  File "/Users/luckydonald/Documents/Python/virtualenv3.4.3_brew.venv/lib/python3.4/site-packages/scapy/packet.py", line 195, in __getattr__
    return fld.i2h(self, v)
  File "/Users/luckydonald/Documents/Python/virtualenv3.4.3_brew.venv/lib/python3.4/site-packages/scapy/fields.py", line 260, in i2h
    iff,x,gw = conf.route.route(dst)
AttributeError: 'NoneType' object has no attribute 'route'
```

Mac OSX 10.9.5
```shell
mac:SimpleStuff luckydonald$ uname -a
Darwin mac.fritz.box 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64
```
```python
Python 3.4.3 (default, Aug 10 2015, 16:40:44) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
```

**Comment by luckydonald** [comment]
Okey, it works when starting in interactive mode
```python
from scapy.main import interact

interact()
````
What am i missing?

**Comment by phaethon** [comment]
Normally you start from python interpreter with `from scapy.all import *`.
Or you can start scapy from shell with `sudo scapy` if it is in the path. This way you don't need to import anything.

**Comment by phaethon** [comment]
Closing, as no more comments received for 2 weeks.

**Comment by luckydonald** [comment]
jep.
