### ISSUE TITLE
bytes(SCTP()) fails

### ISSUE THREAD

**Issue by bartex80** [phaethon/scapy#48]
```
>>> bytes(SCTP())
Traceback (most recent call last):
  File "/usr/lib/python3.4/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/tmp/scapy3/scapy/packet.py", line 289, in __bytes__
    return self.build()
  File "/tmp/scapy3/scapy/packet.py", line 357, in build
    p = self.do_build()
  File "/tmp/scapy3/scapy/packet.py", line 350, in do_build
    p = self.post_build(pkt,pay)
  File "/tmp/scapy3/scapy/layers/sctp.py", line 204, in post_build
    crc = crc32c(str(p))
  File "/tmp/scapy3/scapy/layers/sctp.py", line 92, in crc32c
    crc = (crc>>8) ^ crc32c_table[(crc^(c)) & 0xFF]
TypeError: unsupported operand type(s) for ^: 'int' and 'str'
```

$ python3 --version
Python 3.4.3+

**Comment by phaethon** [comment]
Specific issue now is fixed. Probably SCTP needs more testing. Please, comment your success with SCTP.
