### ISSUE TITLE
Python 3.5.1, Windows 7/64 Import stack trace

### ISSUE THREAD

**Issue by apiszcz** [phaethon/scapy#74]
FYI

>>> from scapy.all import *
WARNING: Windows support for scapy3k is currently in testing. Sniffing/sending/receiving packets should be working with
WinPcap driver and Powershell. Create issues at https://github.com/phaethon/scapy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib\scapy\all.py", line 16, in <module>
    from .arch import *
  File "lib\scapy\arch\__init__.py", line 88, in <module>
    from .windows import *
  File "lib\scapy\arch\windows\__init__.py", line 200, in <module>
    ifaces.load_from_powershell()
  File "lib\scapy\arch\windows\__init__.py", line 151, in load_from_powershell
    for i in get_windows_if_list():
  File "lib\scapy\arch\windows\__init__.py", line 87, in get_windows_if_list
    name, value = [ j.strip() for j in i.split(':') ]
ValueError: too many values to unpack (expected 2)

**Comment by phaethon** [comment]
Out of the box scapy3k is not supporting Windows 7. You can see #50 for possible patches.
