### ISSUE TITLE
CharEnumField throws TypeError during instantiation

### ISSUE THREAD

**Issue by devanlai** [phaethon/scapy#83]
Using a `CharEnumField` throws a `TypeError` when it attempts to index into the enum dictionary keys, which are `dict_keys` objects in python3 instead of lists.

I'm using scapy-python3 version 0.18 and python 3.5.1

Traceback:
```
Traceback (most recent call last):
  File "bug.py", line 3, in <module>
    class SomeLayer(Packet):
  File "bug.py", line 5, in SomeLayer
    CharEnumField("foo", "X", {"X": 1, "Y": 2})
  File "/usr/local/lib/python3.5/dist-packages/scapy/fields.py", line 766, in __init__
    if k and len(k[0]) != 1:
TypeError: 'dict_keys' object does not support indexing
```

Snippet to reproduce:
```
from scapy.all import *

class SomeLayer(Packet):
    fields_desc = [
        CharEnumField("foo", "X", {"X": 1, "Y": 2})
    ]
```

Converting the keys to a list first seems like a straightforward fix, i.e.:
````
class CharEnumField(EnumField):
    def __init__(self, name, default, enum, fmt = "1s"):
        EnumField.__init__(self, name, default, enum, fmt)
        k = list(self.i2s.keys())
        if k and len(k[0]) != 1:
            self.i2s,self.s2i = self.s2i,self.i2s
````

**Comment by phaethon** [comment]
Thanks for the report. Can you create a pull request?
