### ISSUE TITLE
RandNum & int

### ISSUE THREAD

**Issue by qutorial** [phaethon/scapy#99]
fuzz(IP()).show()
###[ IP ]###
  version   = 5
  ihl       = None
  tos       = 218
  len       = None
  id        = 57219
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zaur/diode/smtests/env/lib/python3.5/site-packages/scapy/packet.py", line 863, in show
    reprval = f.i2repr(self,fvalue)
  File "/home/zaur/diode/smtests/env/lib/python3.5/site-packages/scapy/fields.py", line 893, in i2repr
    if x & 1:
TypeError: unsupported operand type(s) for &: 'RandNum' and 'int'

**Comment by TheRealTaiLopez** [comment]
I was able to reproduce the bug fairly easily on Ubuntu 16.0.4 using Python 3.5.2 as shown below.
![reproducing the bug](https://cloud.githubusercontent.com/assets/21000551/17975214/dbc8df5e-6ab6-11e6-9a26-284ade1a8d6f.png)

I then ran a regular _IP().show()_ just for a comparison.
![an interesting observation](https://cloud.githubusercontent.com/assets/21000551/17975271/0ee27332-6ab7-11e6-9376-c177323389ae.png)

It was here that I observed that the flags field was empty or not being set.
![flags not set](https://cloud.githubusercontent.com/assets/21000551/17975318/3bc36c3a-6ab7-11e6-986c-00e3c2722eab.png)

On a whim I tried _fuzz(IP()).show()_ again, though this time I manually set the flags instead of letting them be randomly set by fuzz. The result was that this time the function succeeded in printing the packet as shown below.

![works fine when flags are set](https://cloud.githubusercontent.com/assets/21000551/17975644/82adc414-6ab8-11e6-9b7f-32aec5460008.png)
![works fine when flags are set second example](https://cloud.githubusercontent.com/assets/21000551/17975647/85db511a-6ab8-11e6-8ff2-59ffd200fb1b.png)
